---
apiVersion: v1
kind: Service
metadata:
  name: web2
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  web2_mapping
      prefix: /web2/
      service: web2
spec:
  selector:
    app: web2
  ports:
  - port: 80
    name: web2
    targetPort: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - name: web2
        image: bartr/go-web-aks
        ports:
        - name: http
          containerPort: 8080
