apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-go
spec:
  selector:
    matchLabels:
      app: nginx-go
  template:
    metadata:
      labels:
        app: nginx-go
    spec:
      containers:
      - name: nginx-go
        image: bartr/nginx-go
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
          limits:
            cpu: 750m
            memory: 256Mi
        ports:
        - containerPort: 80
        - containerPort: 443
        livenessProbe:
          exec:
            command:
              - cat
              - /root/app/logs/app.log
          initialDelaySeconds: 60
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 5
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
                fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
                fieldPath: metadata.name
